site_name: pytorch-sparse-utils
theme:
  name: readthedocs
repo_url: https://github.com/mawright/pytorch-sparse-utils

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
          paths: [pytorch_sparse_utils]

nav:
  - Home: index.md
  - Indexing: indexing.md
  - Batching: batching.md
  - MinkowskiEngine and spconv: me_sp.md